import { Navbar } from "@/components/views/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Wrapper from "@/components/shared/Wrapper";
import Footer from "@/components/views/Footer";

import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Wrapper>
            <Navbar />
            {children}
            <Footer />
          </Wrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
